name: uikit
description: UIKit components layer.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
    
  fluttertoast: ^8.2.2
  dropdown_button2: ^2.1.4
  flutter_typeahead: ^4.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: